### PR TITLE
Updated the result directory

### PR DESCRIPTION
**Pull request by mrrajan**
Signed-off-by: Rajan Ravi <rravi@redhat.com>

Jenkins couldnt reach the environment variables set by export command. Mitigated the issue by using a temp file.

### CODE REVIEW

**Review by harshkumarRH — COMMENTED** [review]
@mrrajan should we also remove this temp file at the end of rp_uploader.sh so that we never have any residual from previous runs. This will eliminate any possibility of old results being re uploaded in case result_dir fails to get created for any reason
LMKYT

**Comment by mrrajan** [comment]
@harshkumarRH This will help us in Jenkins pipelines and the file result_dir would be created under Jenkins workspace. Since we are already segregating the Jenkins workspace for each builds - I hope the result_dir will have reference to recent results.

**Comment by ikanias** [comment]
@mrrajan @harshkumarRH I believe that the file created will have the date and time from the artifact so I believe we can distinguish the old results from the new ones(like Rajan said it is per workspace)

**Review by ikanias — APPROVED** [review]
LGTM

**Review by harshkumarRH — APPROVED** [review]
LGTM

**Pull request merged**
